title: Craft Coder - Learn by Doing
description: Let's learn a lot with a bunch of code examples
google_analytics: UA-91011761-1
theme: jekyll-theme-cayman
twitter_username:     alexandregamma
github_username:      alexandregama
linkedin_username:    alexandregama
google_plus_username: alexandregama
facebook_username:    alexandre.gama.lima

gems:
  - jekyll-seo-tag
